---
title: "Prediction with new data for intercept - Supplementary material"
format: 
  html:
    number-sections: True
    fig-height: 10
    fig-width: 8
editor: source
execute: 
  echo: FALSE
---

```{r include = FALSE}
library(tidyverse)
library(ggplot2)
library(DBI)
library(RSQLite)
library(here)
library(glue)

# Loading files:
sim_name <- "240211_cluster-x"
results_folder <- here("Results", "Database-extracts", sim_name)

my_n_studies <- 32
my_icc <- 0.05

icc_vector <- c(0.05, 0.2)


cbp2 <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#CC79A7")
```

## Var_u
```{R}
var_u <- readRDS(file = here(results_folder, "var_u.RDS")) |> 
  filter(model != "Random intercept - ML", model != "Hausman - centred") |> 
  ProfacSims:::correct_model_spelling()

```


## Calibration in the large
```{R}
calib_itl <- readRDS(file = here(results_folder, "calib_itl.RDS")) |> 
  filter(model != "Random intercept - ML", model != "Hausman - centred") |> 
  ProfacSims:::correct_model_spelling()

```




```{r cluster_x_calib_itl_hetro_small, fig.height = 4}
my_n_studies <- 4
my_icc <- 0.05
my_study_size <- 50

calib_itl$plot_value <-  sqrt(calib_itl$tau2)
    plot_data <- calib_itl |> filter(n_studies ==my_n_studies, ICC == my_icc, study_sample_size_train == my_study_size) 
      plot <- plot_data |> 
        ProfacSims:::box_plot_cluster_x_main() + # 
        ylab(glue("Tau")) +
        labs(
              title = "Between Study Hetrogeneity in Calibrtion in the Large",
              subtitle = glue("Training data: {my_n_studies} studies, of size {my_study_size}. ICC: {my_icc}")
            ) +  
        scale_y_continuous(limits = c(0, 0.4)) 
           

        
      
        print(plot)

```



## Calibration Slope
```{R}
calib_slope <- readRDS(file = here(results_folder, "calib_slope.RDS")) |> 
  filter(model != "Random intercept - ML", model != "Hausman - centred") |> 
  ProfacSims:::correct_model_spelling()

```

### Estimates
```{r cluster_x_calib_slope_est}
calib_slope$plot_value = calib_slope$est
    plot_data <- calib_slope |> filter(n_studies ==my_n_studies) 
      plot <- plot_data |> 
        ProfacSims:::box_plot_cluster_x_main() + # 
        ylab(glue("Calibration Slope")) +
        labs(
              title = "Calibration Slope",
              subtitle = glue("Training data: {my_n_studies} studies, ICC: {my_icc}")
            ) +  
        scale_y_continuous(limits = c(0.75, 1.75)) 
           

        
      
        print(plot)

```

```{r cluster_x_calib_slope_est_small}
calib_slope$plot_value = calib_slope$est
    plot_data <- calib_slope |> filter(n_studies ==4) 
      plot <- plot_data |> 
        ProfacSims:::box_plot_cluster_x_main() + # 
        ylab(glue("Calibration Slope")) +
        labs(
              title = "Calibration Slope",
              subtitle = glue("Training data: 4 studies, ICC: {my_icc}")
            ) +  
        scale_y_continuous(limits = c(0.75, 1.75)) 
           

        
      
        print(plot)

```




## MSE
```{R}
mse <- readRDS(file = here(results_folder, "mse.RDS")) |> 
  filter(model != "Random intercept - ML", model != "Hausman - centred") |> 
  ProfacSims:::correct_model_spelling()

```

```{r cluster_x_mse_est}
mse$plot_value = mse$est

    plot_data <- mse |> filter(n_studies ==my_n_studies) 
      plot <- plot_data |> 
        ProfacSims:::box_plot_cluster_x_main() + # 
        ylab(glue("Mean Squared Error")) +
        labs(
              title = "Mean Squared Error",
              subtitle = glue("Training data: {my_n_studies} studies, ICC: {my_icc}")
            ) +  scale_y_continuous(limits = c(0.595, 0.6325))

      
        print(plot)

```
