---
title: "240131-level-2-endo - Model Performance"
format: html
params:
  what: "Calibration In the Large"
  file_name: "calib_itl"
  sim_name: "240206-lvl2-endo"
---


```{r echo = FALSE}
library(tidyverse)
library(ggplot2)
library(DBI)
library(RSQLite)
library(here)
library(glue)

what <- params$what
sim_name <- params$sim_name
file_name <- paste0(params$file_name, ".RDS")

# Loading files:
results_folder <- here("Results", "Database-extracts", sim_name)

data_raw <- readRDS(file = here(results_folder, file_name)) 
data <- data_raw |> dplyr::filter(model != "Random intercept - ML", model != "Hausman - centred") |> tibble()
cn <- colnames(data)


```




## Calib ITL

```{r echo = FALSE}
for(myStudySize in c(50, 200, 1000)){
  for(myICC in c(0.05, 0.2)){
  plot <- data |> mutate(plot_value = est) |> 
    filter(study_sample_size_train == myStudySize, ICC == myICC) |> 
    ProfacSims:::box_plot_lvl2_endo() +
    ylab(glue("{what}")) +
    labs(title = glue("{what}"), subtitle = glue("Study sample size: {myStudySize}, ICC: {myICC}")) +
    scale_y_continuous(breaks = c(-0.2, 0, 0.2), limits = c(-0.2, 0.2))    

  
  print(plot)
  
  }
}



```
## Tau

```{r echo = FALSE}
for(myStudySize in c(50, 200, 1000)){
  for(myICC in c(0.05, 0.2)){
  plot <- data |> mutate(plot_value = sqrt(tau2)) |> 
    filter(study_sample_size_train == myStudySize, ICC == myICC) |> 
    ProfacSims:::box_plot_lvl2_endo() +
     ylab(glue("Tau")) +
    scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3), limits = c(0, 0.3))   + 

    labs(title = glue("Between study hetrogeneity in {what}"), subtitle = glue("Study sample size: {myStudySize}, ICC: {myICC}"))
  
  print(plot)
  
  }
}

```
