---
title: "Prediction with new data for intercepts"
format: html
editor: source
---

```{r echo = FALSE}
library(tidyverse)
library(ggplot2)
library(DBI)
library(RSQLite)
library(here)
library(glue)

# Loading files:
sim_name <- "240124-pred-new-data"
results_folder <- here("Results", "Database-extracts", sim_name)

data <- readRDS(file = here(results_folder, "r_squared.RDS"))
data_new0 <- data |> filter(predict_method == "new0", intercept_est_sample_size ==10) |> 
  mutate(intercept_est_sample_size = 0)

data <- data |> filter(predict_method!= "new0") |> bind_rows(data_new0)



```

## Ns

```{r, echo = FALSE}
counts = data |> 
  group_by(n_studies, ICC, R2, study_sample_size_train, model, predict_method, intercept_est_sample_size) |> 
  summarise(n_est = sum(!is.na(est)), n_tau = sum(!is.na(tau2)))

print("Estimates")
min(counts$n_est)
max(counts$n_est)   


print("Tau-squared")
min(counts$n_est)
max(counts$n_est)        
```

## R-Squared

```{r, fig.height = 8}
for(myICC in c(0, 0.05, 0.2)){
    for(sample_size_train in c(50, 200, 1000)){
    plot <- data |> 
      ProfacSims:::box_plot_ml_fixed(what = "tau", ylab = "Tau", facet_rows = ggplot2::vars(intercept_est_sample_size), facet_cols = ggplot2::vars(R2)) +
      labs(title = "Between study hetrogeneity in R-squared",
        subtitle = glue("ICC = {myICC}, study sample size = {sample_size_train}"))
    
    print(plot)
        
    }
  }

```
