---
title: "Prediction with new data for intercepts"
format: html
editor: visual
---

```{r echo = FALSE}
library(tidyverse)
library(ggplot2)
library(DBI)
library(RSQLite)
library(here)
library(glue)

# Loading files:
sim_name <- "240124-pred-new-data"
results_folder <- here("Results", "Database-extracts", sim_name)

calib_itl_raw <- readRDS(file = here(results_folder, "calib_itl.RDS"))

calib_itl <- calib_itl_raw |> filter(model != "Not adjusting for study") |> 
  filter(!(predict_method == "new0" & model != "Fixed intercept"))
```

## Ns

```{r, echo = FALSE}
counts = calib_itl |> 
  group_by(n_studies, ICC, R2, study_sample_size_train, model, predict_method, intercept_est_sample_size) |> 
  summarise(n_est = sum(!is.na(est)), n_tau = sum(!is.na(tau2)))

print("Estimates")
min(counts$n_est)
max(counts$n_est)   


print("Tau-squared")
min(counts$n_est)
max(counts$n_est)        
```
## Diffs:

Does fixed intercept change with sample size or n_studies?

```{r}
wide_est <- calib_itl |>
  filter(model == "Fixed intercept") |> 
   select(n_studies, ICC, R2, study_sample_size_train, tau2, batch_no, model, intercept_est_sample_size, predict_method) |>
   pivot_wider(names_from = "study_sample_size_train", values_from = "tau2")




```

## Table
```{r, echo = FALSE}

full_table <- calib_itl |> 
  group_by(model, predict_method, n_studies, study_sample_size_train, ICC, R2, intercept_est_sample_size) |> 
   ProfacSims:::quantiles_table_tau() 

print(full_table)

extreme_table <- full_table |> filter(p005 < -0.1 | p95 > 0.1)

extreme_table |> filter(predict_method == "new0")
extreme_table |> filter(predict_method != "new0")

```

Fixed intercept, average intercepts, when ICC is 0.05 or 0.2 has variable Calib In The Large.

Random intercept models, estimated with maximum liklihood, when number of studies is 4, sample size 50, new dynamic or new_studies.

counts = calib_itl

## Calibration in the large

```{r, echo = FALSE}
what = "tau"
ylab = "Calibration in the Large"
```

```{r, fig.height = 6}
for(myICC in c(0, 0.05, 0.2)){
  for(R2 in c(0.4, 0.7)){
    for(sample_size_train in c(50, 200, 1000)){
      

    plot <- calib_itl |> 
      filter(model %in% c("Fixed intercept", "Random intercept - REML"), 
             predict_method %in% c("new0", "new_studies")) |> 
      box_plot_ml_fixed(what = "tau", ylab = "Between study hetrogeneity (Tau)", facet_rows = ggplot2::vars(intercept_est_sample_size))
    
    print(plot)
        
    }
  }
}
```
  
## ICC = 0
```{r, fig.height = 6}
for(what in c("tau")){
  for(n_studies in c(4,8,16,32,64)){
      for(sample_size_train in c(50, 200, 1000)){
        for(myICC in c(0)){
          for(myR2 in c(0.4, 0.7)){
            for(intercept_est_sample_size in c(10, 50, 200)){
             
          plot_data <- calib_itl |> 
            filter(intercept_est_sample_size ==10) |> 
           filter(R2 == myR2, 
                  ICC == myICC, 
                  n_studies == n_studies, 
                  study_sample_size_train == sample_size_train,
                  model %in% c("Fixed intercept", "Random intercept - REML"))
          plot <- plot_data |> 
            ProfacSims:::box_plot_by_predict_method(what = what, ylab = what)
          
          plot <- plot + labs(
            title = "Calibration in the large",
            subtitle = glue("R-sqaured = {myR2}, ICC = {myICC}, Number of studies == {n_studies}, study sample size = {sample_size_train}"))
          print(plot)
  
            }
          }
        }
      }
    }
  }



```

# 10 people for prediction

```{r, fig.height = 6}
for(what in c("tau")){
  for(n_studies in c(4,8,16,32,64)){
      for(sample_size_train in c(50, 200, 1000)){
        for(myICC in c(0.05, 0.2)){
          for(myR2 in c(0.4, 0.7)){
             
          plot_data <- calib_itl |> 
            filter(intercept_est_sample_size ==10) |> 
           filter(R2 == myR2, 
                  ICC == myICC, 
                  n_studies == n_studies, 
                  study_sample_size_train == sample_size_train)
          plot <- plot_data |> 
            ProfacSims:::box_plot_by_predict_method(what = what, ylab = what)
          
          plot <- plot + labs(
            title = "Calibration in the large",
            subtitle = glue("R-sqaured = {myR2}, ICC = {myICC}, Number of studies == {n_studies}, study sample size = {sample_size_train}"))
          print(plot)
  
            
        }
      }
    }
  }
}


```

